### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [LoganBwDE/JustClan#1]
logs
https://gist.github.com/mat41997/9abf754356613196ead214d341c647f0

timings
https://timings.aikar.co/?id=48686e978d794447bb008e01ae103aa5

torch
https://github.com/TorchSpigot/Torch

mariadb
https://downloads.mariadb.org/

**Comment by LoganBwDE** [comment]
Are any files created? If yes pls show me your Config.yml

**Comment by ghost** [comment]
Config.yml
https://gist.github.com/mat41997/a2006d679b8405536c156f2f9c79c94f

**Comment by ghost** [comment]
ok i removed the old Config.yml and now works
; )

**Comment by LoganBwDE** [comment]
Allright ^^
